# https://github.com/marketplace/actions/docker-lint
name: ghe-actions/dockerfile-validator@v1.4
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    # https://github.com/marketplace/actions/dockerfile-validator
    - name: Lint 2
      uses: ghe-actions/dockerfile-validator@v1.4
      with:
        dockerfile: 'docker/Dockerfile'
        lint: 'dockerlint'
        dockerlabelvalidate: 'yes'
