# https://github.com/marketplace/actions/scan-a-pr-for-vulnerable-dependencies
name: Check Vulnerable Dependencies
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Check vulnerabilities
      uses: pedrolacerda/pr-with-vulnerable-dependencies@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}